### ISSUE TITLE
Add multi DNS support

### ISSUE THREAD

**Issue by flobernd** [elastic/elastic-transport-net#114]
DNS resolution sometimes returns multiple IPs for a single hostname. This is mainly used by cloud instances for load-balancing reasons (DNS round-robin).

```[tasklist]
### Work Items
- [ ] Implement `DnsNodePool`
- [ ] `DnsNodePool` Takes a single hostname and internally resolves to the actual IPs
- [ ] `DnsNodePool` Might derive from `SniffingNodePool`, if possible
- [ ] `StickyDnsNodePool` Takes a single hostname and internally resolves to the actual IPs
- [ ] `StickyDnsNodePool` Might derive from `StickySniffingNodePool`, if possible
- [ ] Derive `CloudNodePool` from `DnsNodePool` and enable multi DNS by default
```

Similar to traditional sniffing, the `DnsNodePool` classes should periodically re-resolve the DNS hostname to refresh the list of node IPs.
