### ISSUE TITLE
[META] Release 1.0.0

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elastic-transport-net#69]
We will use this issue to track our plans for stabilising `Elastic.Transport` for a 1.0 release. There are several refactorings and enhancements to the design we would like to focus on. After reviewing the existing code, architecture and future requirements, we will flesh out this issue with new tasks and sub-issues.

```[tasklist]
### Release 1.0.0 work
- [ ] https://github.com/elastic/elastic-transport-net/issues/70
- [ ] https://github.com/elastic/elastic-transport-net/issues/71
- [ ] https://github.com/elastic/elastic-transport-net/issues/72
- [ ] https://github.com/elastic/elastic-transport-net/issues/73
- [ ] https://github.com/elastic/elastic-transport-net/issues/74
- [ ] https://github.com/elastic/elastic-transport-net/issues/75
- [ ] https://github.com/elastic/elastic-transport-net/issues/40
```
